[package]
name = "genemichaels"
description = "Makes your code formatty"
version = "0.5.4"
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
syn = { workspace = true }
walkdir = "2"
threadpool = "1"
cargo-manifest = "0.15"
aargvark = { version = "0.6" }
console = "0.15"
loga = "0.5"
serde = { workspace = true }
serde_json = { workspace = true }
genemichaels-lib = { version = "=0.5.3", path = "../genemichaels-lib" }
