[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2021"
license = "ISC"

[workspace.dependencies]
syn = { version = "2", features = ["full"] }
loga = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
