[package]
name = "aargvark"
version = "0.0.1"
edition = "2021"
license = "ISC"
description = "Self-similar argument parsing"
homepage = "https://github.com/andrewbaxter/aargvark"
repository = "https://github.com/andrewbaxter/aargvark"
readme = "readme.md"

[workspace]
members = ["src/proc_macros"]

[features]
default = []
serde_json = ["dep:serde_json"]
serde_yaml = ["dep:serde_yaml"]
chrono = ["dep:chrono"]

[dependencies]
anyhow = "1.0.66"
once_cell = "1.16.0"
regex = { version = "1.7.0", default-features = false, features = ["std"] }
aargvark_proc_macros = { path = "src/proc_macros", version = "0.0.1" }
chrono = { version = "0.4.26", optional = true }
serde_json = { version = "1.0.96", optional = true }
serde_yaml = { version = "0.9.21", optional = true }
convert_case = "0.6.0"
comfy-table = "7.0.0"
