on:
  pull_request:
    types: [opened, synchronize]

jobs:
  confirm_agreement:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: ${{ github.event.pull_request.body }}
        run: |
          set -xeu
          if ! grep -F "$(tail -n 1 .github/pull_request_template.md)" <(echo "$BODY"); then
             gh pr close --comment "All changes must agree to copyright assignment." --delete-branch 1
          fi
