on:
  pull_request:
    types: [opened, synchronize]

jobs:
  confirm_agreement:
    runs-on: ubuntu-latest
    steps:
      - env:
          BODY: ${{ github.event.pull_request.body }}
        run: grep -Fxq "$(cat .github/pull_request_template.md)" <(echo "$BODY")
