[package]
name = "aargvark_proc_macros"
description = "Helper crate for aargvark"
version = "3.2.2"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6"
darling = "0.20.10"
genemichaels-lib = "0.5.1"
proc-macro2 = "1"
quote = "1"
syn = "2"
